name: Scan Lua Code for Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Lua 5.0.1
        run: |
          sudo apt update && sudo apt install -y build-essential libreadline-dev
          curl -R -O http://www.lua.org/ftp/lua-5.0.1.tar.gz
          tar zxf lua-5.0.1.tar.gz
          cd lua-5.0.1 && make linux && sudo make install

      - name: Run Lua Safety Check
        run: lua lua_safety_check.lua
